services:
  - type: web
    name: youtubeshorts-backend
    env: docker
    region: singapore
    plan: free
    dockerfilePath: ./backend/Dockerfile
    numInstances: 1
    healthCheckPath: /
